version: 0.1
   
phases:
  install:
    commands:
      - gem install bundler
      - gem install rouge
      - bundle install --full-index #gem install jekyll bundler #jekyll-paginate jekyll-sitemap jekyll-gist
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - bundle exec jekyll build
      - echo "******** Uploading to S3 ********"
      - aws s3 sync --acl public-read --delete _site/ s3://dev-static-blog-0346
